### ISSUE TITLE
Replace lua with Roslyn engine (multiple script languages support)

### ISSUE THREAD

**Issue by tgiachi** [tgiachi/Neon.HomeControl#3]
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell?view=pscore-6.2.0

**Comment by GlennArens** [comment]
Why not support multiple scripting styles?

**Comment by fabioravila** [comment]
What about add support to c# scripting, I can help with this is you want.

**Comment by tgiachi** [comment]
Sure @fabioravila i ve made branch for the issue !

**Comment by fabioravila** [comment]
Ok, i like to help, a already made some of this on .Net full in one of my repo, and I like home automation.
Just tell the branch or issue for me, so I make a start point

**Comment by tgiachi** [comment]
The branch is #3_powershell !

**Comment by fabioravila** [comment]
Oh, so you just start a c# script on this branch.

My plan is to use Roslyn engine, not powershell
And  put some abstractions to a common scriptengine, so we can attach other
languages.

Is this ok for you?

**Comment by tgiachi** [comment]
@fabioravila It's ok!
Fell free to modify!

**Comment by tgiachi** [comment]
Hi @fabioravila ! What is the status of the issue? Thanks!

**Comment by tgiachi** [comment]
I'll take care of issue

**Comment by fabioravila** [comment]
Sorry Tommaso,
I ran out of time to handle this issue.
I really apologize if it bothered you


Em seg, 5 de ago de 2019 às 07:29, Tommaso Giachi <notifications@github.com>
escreveu:

**Comment by tgiachi** [comment]
Now we have script Engine abstraction, by default Neon uses LUA but we implements others engine (I've added JS engine draft)
